# Generated by Django 3.0.8 on 2020-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_address_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='fvf', max_length=50),
            preserve_default=False,
        ),
    ]
